name: grocery_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  go_router: ^12.1.0
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0
  uuid: ^4.5.1
  mime: ^1.0.6
  path: ^1.9.0
  http: ^1.2.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1

  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  xml: ^6.5.0
  image_picker: ^1.2.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  glados: ^1.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
